version: '3'
services:
  app:
    ports:
      - "3080:80"
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - backend
    env_file:
      - .env


networks:
  backend:
    external: true