version: '3'

networks:
  backend:
    external: true

services:
  app:
    hostname: luke-portfolio
    tty: true
    image: registry.lukestoodley.com/luke/portfolio:latest
    restart: always
    networks:
      - backend
    ports:
      - 3650:3000