name: Shiro Stable

on:
  push:
    file: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build: 
    name: Build Image
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: build docker image
      env:
        docker_image_name: registry.lukestoodley.com/luke/portfolio
      run: |
        docker build -t $docker_image_name:latest .
  push-to-registry:
    name: Push to Registry
    needs: build
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Push to Registry
      env:
        registry_user: ${{ secrets.REGISTRY_USERNAME }}
        registry_password: ${{ secrets.REGISTRY_PASSWORD }}
        docker_image_name: registry.lukestoodley.com/luke/portfolio
      run: |
        docker login -u $registry_user -p $registry_password registry.lukestoodley.com
        docker push $docker_image_name:latest
  # prod_deploy:
  #   needs: prod_push_to_registry
  #   if: ${{ contains(github.event.head_commit.message, '(stable)') }}
  #   name: Prod - Deploy update
  #   runs-on: self-hosted
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: deploy
  #     run: |
  #       ssh luke@192.168.122.222 'cd /home/luke/Shiro-Development/Bot && docker-compose pull app-prod && docker-compose up -d -t 0'
