name: Shiro Stable

on:
  push:
    file: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build: 
    name: Build Image
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: build docker image
      env:
        docker_image_name: registry.lukestoodley.com/luke/portfolio
      run: |
        docker build -t $docker_image_name:latest .
  push-to-registry:
    name: Push to Registry
    needs: build
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Push to Registry
      env:
        registry_user: ${{ secrets.REGISTRY_USERNAME }}
        registry_password: ${{ secrets.REGISTRY_PASSWORD }}
        docker_image_name: registry.lukestoodley.com/luke/portfolio
      run: |
        docker login -u $registry_user -p $registry_password registry.lukestoodley.com
        docker push $docker_image_name:latest
  deploy:
    needs: push-to-registry
    name: Deploy changes
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: deploy
      run: |
        ssh root@192.168.122.1 'cd /root/shiro/portfolio && docker-compose pull && docker-compose up -d -t 0'
